services:
  cronicle:
    build: ./Cronicle
    image: cronicle_pentaho:latest
    container_name: cronicle_pentaho
    ports:
      - "3012:3012"
    volumes:
      - ./Cronicle/Pentaho/jobs:/opt/pentaho/jobs
    environment:
      - PENTAHO_HOME=/opt/pentaho/data-integration
      - PATH=/opt/pentaho/data-integration:$PATH
    restart: always
